#!/usr/bin/env python
'''
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
'''
import time

start = time.perf_counter()

lim = 4000000
a = 1
b = 2
c = 0
sum = 2
print(a)
print(b)

while sum < lim:
    if c < lim and c % 2 == 0:
        sum += c
        print(f"{c}*")
    elif c % 2 != 0:
        print(c)
    c = a + b
    a = b
    b = c
    


print(f"sum: {sum}")
print(time.perf_counter()-start)